### ISSUE TITLE
have internal error

### ISSUE THREAD

**Issue by lnh089** [rgtk/redmine_editauthor#25]
Hello,
when I change the issue's author and save, it show internal error,and the nignx log as below:
App 15690 stderr: = Running after_save custom workflows for Issue (#444) "问题 #444: 11111111111"
App 15690 stderr: = Finished running after_save custom workflows for Issue (#444) "问题 #444: 11111111111"
App 15690 stderr:   Rendered mailer/_issue.text.erb (6.7ms)
App 15690 stderr:   Rendered mailer/issue_edit.text.erb within layouts/mailer (14.4ms)
App 15690 stderr:   Rendered mailer/_issue.html.erb (2.2ms)
App 15690 stderr:   Rendered mailer/issue_edit.html.erb within layouts/mailer (8.7ms)
App 15690 stderr: Completed 500 Internal Server Error in 516ms (ActiveRecord: 36.0ms)
App 15690 stderr:
App 15690 stderr: Errno::ECONNREFUSED (Failed to open TCP connection to 192.168.2.16:9292 (Connection refused - connect(2) for "192.168.2.16" port 9292)):
App 15690 stderr:   plugins/redmine_app_notifications/app/models/app_notification.rb:13:in `deliver'
App 15690 stderr:   plugins/redmine_app_notifications/lib/app_notifications_journals_patch.rb:32:in `block in create_app_notifications_after_create_journal'
App 15690 stderr:   plugins/redmine_app_notifications/lib/app_notifications_journals_patch.rb:24:in `each'
App 15690 stderr:   plugins/redmine_app_notifications/lib/app_notifications_journals_patch.rb:24:in `create_app_notifications_after_create_journal'
App 15690 stderr:   app/models/journal.rb:67:in `save'
App 15690 stderr:   app/models/issue.rb:1691:in `create_journal'
App 15690 stderr:   app/models/issue.rb:211:in `create_or_update'
App 15690 stderr:   app/controllers/issues_controller.rb:516:in `block in save_issue_with_child_records'
App 15690 stderr:   app/controllers/issues_controller.rb:504:in `save_issue_with_child_records'
App 15690 stderr:   app/controllers/issues_controller.rb:179:in `update'
App 15690 stderr:   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
and I add the port 9292 to public zone ,but still show error,what is the misstake?thanks.

**Comment by lnh089** [comment]
it is work OK,my redmine have some error
