### ISSUE TITLE
Error 500 opening issue page (redmine 2.3.4.stable on Windows)

### ISSUE THREAD

**Issue by bubibubi** [rgtk/redmine_editauthor#31]
I mean page like this
https://redmine.mydomain/issues/1234

```
[1m[35mProject Load (0.0ms)[0m  SELECT "projects".* FROM "projects" WHERE (projects.status = 1 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking'))
  [1m[36mCACHE (0.0ms)[0m  [1mSELECT "issue_statuses".* FROM "issue_statuses" WHERE "issue_statuses"."id" = 4 LIMIT 1[0m
  [1m[35mCACHE (0.0ms)[0m  SELECT "users".id FROM "users" INNER JOIN "groups_users" ON "users"."id" = "groups_users"."group_id" WHERE "users"."type" IN ('Group') AND "groups_users"."user_id" = 3
  [1m[36mCACHE (0.0ms)[0m  [1mSELECT "roles".* FROM "roles" [0m
  [1m[35mCACHE (0.0ms)[0m  SELECT "workflows".* FROM "workflows" WHERE "workflows"."type" IN ('WorkflowTransition') AND "workflows"."old_status_id" = 4 AND (role_id IN (1,2,3,4,5,6) AND tracker_id = 1 AND ((author = 'f' AND assignee = 'f')))
  [1m[36mCACHE (0.0ms)[0m  [1mSELECT "issue_statuses".* FROM "issue_statuses" WHERE "issue_statuses"."id" IN (1, 2, 3, 5, 6, 7)[0m
  [1m[35mCACHE (0.0ms)[0m  SELECT "roles".* FROM "roles" 
  [1m[36mWorkflowPermission Load (0.0ms)[0m  [1mSELECT "workflows".* FROM "workflows" WHERE "workflows"."type" IN ('WorkflowPermission') AND "workflows"."tracker_id" = 1 AND "workflows"."old_status_id" = 4 AND "workflows"."role_id" IN (1, 2, 3, 4, 5, 6)[0m
  [1m[35mCACHE (0.0ms)[0m  SELECT "projects".* FROM "projects" WHERE (projects.status = 1 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking'))
  [1m[36mTracker Load (0.0ms)[0m  [1mSELECT "trackers".* FROM "trackers" INNER JOIN "projects_trackers" ON "trackers"."id" = "projects_trackers"."tracker_id" WHERE "projects_trackers"."project_id" = 7 ORDER BY trackers.position[0m
  [1m[35mIssuePriority Load (0.0ms)[0m  SELECT "enumerations".* FROM "enumerations" WHERE "enumerations"."type" IN ('IssuePriority') AND "enumerations"."active" = 't' ORDER BY enumerations.position ASC
  [1m[36mSQL (1.0ms)[0m  [1mSELECT "members"."id" AS t0_r0, "members"."user_id" AS t0_r1, "members"."project_id" AS t0_r2, "members"."created_on" AS t0_r3, "members"."mail_notification" AS t0_r4, "users"."id" AS t1_r0, "users"."login" AS t1_r1, "users"."hashed_password" AS t1_r2, "users"."firstname" AS t1_r3, "users"."lastname" AS t1_r4, "users"."mail" AS t1_r5, "users"."admin" AS t1_r6, "users"."status" AS t1_r7, "users"."last_login_on" AS t1_r8, "users"."language" AS t1_r9, "users"."auth_source_id" AS t1_r10, "users"."created_on" AS t1_r11, "users"."updated_on" AS t1_r12, "users"."type" AS t1_r13, "users"."identity_url" AS t1_r14, "users"."mail_notification" AS t1_r15, "users"."salt" AS t1_r16, "roles"."id" AS t2_r0, "roles"."name" AS t2_r1, "roles"."position" AS t2_r2, "roles"."assignable" AS t2_r3, "roles"."builtin" AS t2_r4, "roles"."permissions" AS t2_r5, "roles"."issues_visibility" AS t2_r6 FROM "members" LEFT OUTER JOIN "users" ON "users"."id" = "members"."user_id" LEFT OUTER JOIN "member_roles" ON "member_roles"."member_id" = "members"."id" LEFT OUTER JOIN "roles" ON "roles"."id" = "member_roles"."role_id" WHERE "members"."project_id" = 7 AND (users.type='User' AND users.status=1)[0m
  [1m[35m (1.1ms)[0m  SELECT COUNT(*) FROM "issue_categories" WHERE "issue_categories"."project_id" = 7
  [1m[36mSQL (0.0ms)[0m  [1mSELECT "versions"."id" AS t0_r0, "versions"."project_id" AS t0_r1, "versions"."name" AS t0_r2, "versions"."description" AS t0_r3, "versions"."effective_date" AS t0_r4, "versions"."created_on" AS t0_r5, "versions"."updated_on" AS t0_r6, "versions"."wiki_page_title" AS t0_r7, "versions"."status" AS t0_r8, "versions"."sharing" AS t0_r9, "projects"."id" AS t1_r0, "projects"."name" AS t1_r1, "projects"."description" AS t1_r2, "projects"."homepage" AS t1_r3, "projects"."is_public" AS t1_r4, "projects"."parent_id" AS t1_r5, "projects"."created_on" AS t1_r6, "projects"."updated_on" AS t1_r7, "projects"."identifier" AS t1_r8, "projects"."status" AS t1_r9, "projects"."lft" AS t1_r10, "projects"."rgt" AS t1_r11, "projects"."inherit_members" AS t1_r12 FROM "versions" LEFT OUTER JOIN "projects" ON "projects"."id" = "versions"."project_id" WHERE "versions"."status" = 'open' AND (projects.id = 7 OR (projects.status <> 9 AND ( versions.sharing = 'system' OR (projects.lft >= 13 AND projects.rgt <= 26 AND versions.sharing = 'tree') OR (projects.lft < 13 AND projects.rgt > 26 AND versions.sharing IN ('hierarchy', 'descendants')) OR (projects.lft > 13 AND projects.rgt < 26 AND versions.sharing = 'hierarchy'))))[0m
  Rendered issues/_form_custom_fields.html.erb (1.1ms)
  Rendered issues/_attributes.html.erb (32.2ms)
  [1m[35mSetting Load (0.0ms)[0m  SELECT "settings".* FROM "settings" WHERE "settings"."name" = 'plugin_redmine_editauthor' LIMIT 1
  Rendered issues/_form.html.erb (132.9ms)
  Rendered issues/_edit.html.erb (138.1ms)
  Rendered issues/show.html.erb within layouts/base (271.7ms)
Completed 500 Internal Server Error in 526ms

ActionView::Template::Error (undefined method `pluck' for #<Arel::Nodes::Distinct:0x4db9cf8>):
    41:   <%= render :partial => 'issues/attributes' %>
    42: </div>
    43: 
    44: <%= call_hook(:view_issues_form_details_bottom, { :issue => @issue, :form => f }) %>
    45: <% end %>
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_form.html.erb:44:in `block in _app_views_issues__form_html_erb___343850445_41569596'
  app/helpers/application_helper.rb:955:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb___343850445_41569596'
  app/views/issues/_edit.html.erb:8:in `block in _app_views_issues__edit_html_erb___467624147_41534712'
  app/helpers/application_helper.rb:948:in `labelled_form_for'
  app/views/issues/_edit.html.erb:1:in `_app_views_issues__edit_html_erb___467624147_41534712'
  app/views/issues/show.html.erb:132:in `_app_views_issues_show_html_erb__700021579_34282788'
  app/controllers/issues_controller.rb:119:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:116:in `show'
```
My environment

```
Environment:
  Redmine version                2.3.4.stable
  Ruby version                   1.9.3-p448 (2013-06-27) [i386-mingw32]
  Rails version                  3.2.13
  Environment                    development
  Database adapter               SQLite
Redmine plugins:
  no plugin installed
```

**Comment by nounder** [comment]
Support for Redmine 2.x has been dropped.
