### ISSUE TITLE
ActionView::Template::Error (undefined method `unshift') viewing issue assigned to Anonymous user

### ISSUE THREAD

**Issue by xurizaemon** [rgtk/redmine_editauthor#32]
Hi there! Happy to try my hand at resolving this, not a Redmine expert so guidance welcome :grin: 

I'm seeing this error after an issue was created by an email address not associated with a user.

The issue belongs to uid=2, an Anonymous user a/c (guessing this is a Redmine default?)

I see that in [`lib/redmine_editauthor/hook.rb`](https://github.com/rgtk/redmine_editauthor/blob/master/lib/redmine_editauthor/hook.rb#L22) the plugin attempts to catch errors where the author doesn't exist, but the unshift still throws an error (presumably Anonymous user is a special case here?)

Redmine details:
```
Environment:
  Redmine version                3.4.6.devel
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  5.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_editauthor             0.11.0
  redmine_gist                   0.1.1
  redmine_image_clipboard_paste  3.3.0
  redmine_messenger              1.0.3
```

Backtrace:
```
==> /home/redmine/redmine/redmine/log/production.log <==
Started GET "/issues/123" for 1.2.3.4 at 2018-12-18 07:01:44 +1300
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"123"}
  Current user: example.user (id=1)
  Rendering issues/show.html.erb within layouts/base
  Rendered issues/_action_menu.html.erb (4.7ms)
  Rendered issue_relations/_form.html.erb (1.7ms)
  Rendered issues/_relations.html.erb (2.5ms)
  Rendered issues/_action_menu.html.erb (4.6ms)
  Rendered issues/_form_custom_fields.html.erb (0.4ms)
  Rendered issues/_attributes.html.erb (16.2ms)
  Rendered issues/_form.html.erb (49.2ms)
  Rendered issues/_edit.html.erb (50.1ms)
  Rendered issues/_action_menu_edit.html.erb (55.5ms)
  Rendered issues/show.html.erb within layouts/base (91.7ms)
Completed 500 Internal Server Error in 144ms (ActiveRecord: 13.5ms)
  
ActionView::Template::Error (undefined method `unshift' for #<User::ActiveRecord_Relation:0x000000041f6568>):
    44:   <%= render :partial => 'issues/attributes' %>
    45: </div>
    46: 
    47: <%= call_hook(:view_issues_form_details_bottom, { :issue => @issue, :form => f }) %>
    48: <% end %>
    49: 
    50: <% heads_for_wiki_formatter %>
  
plugins/redmine_editauthor/lib/redmine_editauthor/hook.rb:22:in `block in view_issues_form_details_bottom'
plugins/redmine_editauthor/lib/redmine_editauthor/hook.rb:19:in `view_issues_form_details_bottom'
lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:61:in `each'
lib/redmine/hook.rb:61:in `block in call_hook'
lib/redmine/hook.rb:58:in `tap'
lib/redmine/hook.rb:58:in `call_hook'
lib/redmine/hook.rb:96:in `call_hook'
app/views/issues/_form.html.erb:47:in `block in _app_views_issues__form_html_erb__2960696311288320352_47074680'
app/helpers/application_helper.rb:1237:in `labelled_fields_for'
app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb__2960696311288320352_47074680'
app/views/issues/_edit.html.erb:8:in `block in _app_views_issues__edit_html_erb___3052376908758556173_61309540'
app/helpers/application_helper.rb:1230:in `labelled_form_for'
app/views/issues/_edit.html.erb:1:in `_app_views_issues__edit_html_erb___3052376908758556173_61309540'
app/views/issues/_action_menu_edit.html.erb:8:in `_app_views_issues__action_menu_edit_html_erb__3179006967060884851_61477360'
app/views/issues/show.html.erb:137:in `_app_views_issues_show_html_erb__2137193729562061852_60877680'
app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
app/controllers/issues_controller.rb:99:in `show'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by nounder** [comment]
Error is caused by this line: https://github.com/rgtk/redmine_editauthor/blob/9ac40cee9c0e6c293a8401b9b71dd70c3475e990/lib/redmine_editauthor/hook.rb#L22

It happens because `possible_authors` returns `User::ActiveRecord_Relation` and I am calling `unshift` method commonly found in `Array` which Relation is clearly not.

Silly me. Why would I write a code that doesn't work?

It works, but for older version of Rails (framework Redmine use). It seems you use Rails 5.x. I have tested and used this plugin for 3-4.x. 

The way to fix it is to convert Relation to an Array which you can do by calling `to_a` on it:
```authors = possible_authors(issue.project).to_a```

I have not tested it but it should work. Try it! And maybe create pull request? :wink:

**Comment by xurizaemon** [comment]
Done :grin: thanks for the feedback and quick response!

Your proposed fix seems to solve the issue for me.

**Comment by nounder** [comment]
Thanks.
