### ISSUE TITLE
Not compatible with plugin additionals

### ISSUE THREAD

**Issue by sphereweb83** [rgtk/redmine_editauthor#38]
Hello, at Runtime i get this error:

`Message from application:
additionals plugin cannot be used with redmine_editauthor plugin'. (RuntimeError)
  /opt/bitnami/apps/redmine/htdocs/plugins/additionals/lib/additionals.rb:109:in `block in incompatible_plugins'
  /opt/bitnami/apps/redmine/htdocs/plugins/additionals/lib/additionals.rb:108:in `each'
  /opt/bitnami/apps/redmine/htdocs/plugins/additionals/lib/additionals.rb:108:in `incompatible_plugins'
`

**Comment by nounder** [comment]
That's an error thrown by `additionals` plugin. For some reason its author decided that it will not work with following plugins: `redmine_tweaks redmine_issue_control_panel redmine_editauthor redmine_changeauthor redmine_auto_watch`

You should contact author of `additionals` plugin why's that a case. I am eager to work together with him/her so both plugins can live together in peace.

**Comment by nounder** [comment]
Closing due to no activity.
